# Generated by Django 5.0.4 on 2024-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('option_1', models.TextField(blank=True, null=True)),
                ('option_2', models.TextField(blank=True, null=True)),
                ('option_3', models.TextField(blank=True, null=True)),
                ('option_4', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
